help:
	@echo
	@echo "#####FRONTEND COMMANDS #####"
	@echo	
	@echo "fe-install                            -- install frontend dependencies"
	@echo "fe-lint                               -- lint frontend"
	@echo "fe-format                             -- format frontend"
	@echo "fe-dev                                -- start frontend development server"
	@echo "fe-build                              -- build frontend"

fe-install:
	yarn install

fe-lint:
	yarn lint

fe-format:
	yarn format

fe-dev:
	yarn dev

.PHONY: build
fe-build:
	yarn build